#!/bin/bash

sudo apt update
sudo apt install python3-pip
pip3 --version
echo '------------------------------------------------------------'
sudo apt install python3-dev default-libmysqlclient-dev build-essential
