"""this file carries all constants"""

user = 'user'
users = 'users'
first_name = 'first_name'
last_name = 'last_name'
mobile_number = 'mobile_number'
email = 'email'
username = 'username'
date_registered = 'date_registered'
interests = 'interests'

alert_medium = 'alert_medium'
# alert_medium_id = 'alert_medium_id'
# whatsapp_verified = 'whatsapp_verified'
# email_verified = 'email_verified'
# telegram_verified = 'telegram_verified'
user_id = 'user_id'

alerts = 'alerts'
# alert_id = 'alert_id'
condition = 'condition'
comodity = 'comodity'
timeframe = 'timeframe'
setpoint = 'setpoint'
# timeframe = 'timeframe'
alert_medium = 'alert_medium'
repeat_setpoint = 'repeat_setpoint'
expiration = 'expiration'
# alert_count = 'alert_count'

User ='User'
user_foriegn_key =f'{user}.user_id'
AlertMedium = 'AlertMedium'
owner = 'owner'
Alerts = 'Alerts'
user_alerts_column = 'user_alerts'
user_alert_medium_column = 'user_alert_medium'
user_already_exists = 'The User already exist'

my_jwt_secrete = 'My_jwt_secrete'
invalid_credentials = 'Invalid user credentials'
invalid_user_password = 'invalid user name or password'

access_token = 'access_token'
access_type = 'access_type'
exp = 'exp'
expired_token = 'Token has expired'
one_day = 86400

alert_not_found = 'alert not found'
invalid_input = 'invalid input'
alert_has_expired = 'alert has expired'
alert_is_closed = 'alert is closed'
deleted = 'deleted'
